import { useState } from "react";
import type { MouseEventHandler } from "react";
import Head from "next/head";
import { RandomFox } from "@components/RandomFox";

type ImageItem = {
  id: string;
  url: string;
};

//generate simple unique id
const generateId = () => Math.random().toString(36).substring(2, 9);

export default function Home() {
  const random = () => Math.floor(Math.random() * 123) + 1;

  const [images, setImages] = useState<Array<ImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImageItem: ImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`,
    };
    setImages([...images, newImageItem]);
  };
  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by Jorge Niglia" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>
      <div className="m-1 border-2 border-orange-800 rounded-lg shadow-lg bg-gradient-to-r from-yellow-50 via-orange-50 to-red-100 shadow-orange-800">
        <main className="grid justify-center h-full grid-cols-12 ">
          <h1 className="col-span-6 col-start-4 my-4 text-3xl font-bold text-center">
            What does the Fox say?
          </h1>
          <button
            onClick={addNewFox}
            className="h-16 col-span-4 col-start-5 py-2 my-4 text-xl font-bold bg-orange-200 border-2 border-yellow-800 rounded-lg shadow-lg shadow-yellow-900"
          >
            Add new Fox
          </button>
          {images.map(({ id, url }) => (
            <RandomFox key={id} image={url} alt={"fox image"} />
          ))}
        </main>
        <footer className="p-4 text-xl italic font-bold text-center text-orange-800">
          by Jorge Niglia - 2023
        </footer>
      </div>
    </>
  );
}
