import { useState } from "react";
import type { MouseEventHandler } from "react";
import Head from "next/head";
import { LazyImage } from "@components/LazyImage";

let count = 0;
//generate simple unique id
const generateId = () => Math.random().toString(36).substring(2, 9);

export default function Home() {
  const random = () => Math.floor(Math.random() * 123) + 1;

  const [images, setImages] = useState<Array<TImageItem>>([]);
  const [heightScreen, setheightScreen] = useState<string>("h-screen");
  const [count, setCount] = useState(0);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    setCount(count + 1);
    const newImageItem: TImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`,
    };
    setImages([...images, newImageItem]);
    if (count >= 2) {
      setheightScreen("h-full");
    }
    console.log(count);
  };
  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by Jorge Niglia" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>
      <div
        className={`${heightScreen} m-1 border-2 border-orange-800 rounded-lg shadow-lg bg-gradient-to-r from-yellow-50 via-orange-50 to-red-100 shadow-orange-800`}
      >
        <main className="grid justify-center grid-cols-12 ">
          <h1 className="col-span-6 col-start-4 my-4 text-3xl font-bold text-center">
            What does the Fox say?
          </h1>
          <button
            onClick={addNewFox}
            className="h-16 col-span-4 col-start-5 py-2 my-4 text-xl font-bold bg-orange-200 border-2 border-yellow-800 rounded-lg shadow-lg lg:col-span-2 lg:col-start-6 shadow-yellow-900"
          >
            Add new Fox
          </button>
          {images.map(({ id, url }, index) => (
            <LazyImage
              key={id}
              src={url}
              className="w-4/5 h-auto col-span-6 col-start-4 my-4 border-2 border-yellow-800 rounded-lg shadow-lg lg:col-span-4 lg:col-start-5 justify-self-center shadow-yellow-900"
              alt={"fox-image"}
              onLazyLoad={(img) => {
                console.log(`Image #${index + 1} cargada. Nodo:`, img);
              }}
            />
          ))}
        </main>
        <footer className="p-4 text-xl italic font-bold text-center text-orange-800">
          by Jorge Niglia - 2023
        </footer>
      </div>
    </>
  );
}
