import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Platzi</title>
        <meta name="description" content="Generated by Jorge Niglia" />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold text-center">Hello, Platzi</h1>
      </main>
    </>
  );
}
